export const FETCH_DISHES_START = 'FETCH_DISHES_START';
export const FETCH_DISHES_FAIL = 'FETCH_DISHES_FAIL';
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS';
export const CLEAR_DISHES = 'CLEAR_DISHES';

export const FETCH_DISH_START = 'FETCH_DISH_START';
export const FETCH_DISH_FAIL = 'FETCH_DISH_FAIL';
export const FETCH_DISH_SUCCESS = 'FETCH_DISH_SUCCESS';

export const STORE_DISH = 'STORE_DISH';
export const UPDATE_DISH = 'UPDATE_DISH';
export const DELETE_DISH = 'DELETE_DISH';

export const FETCH_FILTERS_START = 'FETCH_FILTERS_START';
export const FETCH_FILTERS_FAIL = 'FETCH_FILTERS_FAIL';
export const FETCH_FILTERS_SUCCESS = 'FETCH_FILTERS_SUCCESS';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const EMIT_FILTERS_CHANGE = 'EMIT_FILTERS_CHANGE';
export const TOGGLE_COLLAPSE_FILTER = 'TOGGLE_COLLAPSE_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';