export const FETCH_DISHES_START = 'FETCH_DISHES_START';
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS';
export const FETCH_DISHES_FAIL = 'FETCH_DISHES_FAIL';

export const STORE_DISH = 'STORE_DISH';
export const DELETE_DISH = 'DELETE_DISH';